config/routes.rb
Rails.application.routes.draw do
  root to: 'orders#index'

  resources :orders, only: %i[index create show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
    validates_presence_of :name
end

app/models/item.rb
class Item < ApplicationRecord
  validates_presence_of :quantity

  belongs_to :order
  belongs_to :product
  belongs_to :supplier
  belongs_to :client
  delegate :price, to: :product
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :items

    def value
        items.includes(:product).sum('price * quantity')
    end
end

app/models/product.rb
class Product < ApplicationRecord
    validates_presence_of :description
    validates_presence_of :price
end

app/models/supplier.rb
class Supplier < ApplicationRecord
    validates_presence_of :name
    validates_presence_of :address

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  skip_before_action :verify_authenticity_token
  
  def index
    @orders = Order.all.order(id: :desc)
  end

  def show
    @order = Order.includes(:items).find(params[:id])
  end

  def create
    order_file = params[:file]
    result = ParseOrderFile.call(file: order_file, locale: :pt)
    @order = result.order 
    respond_to do |format|
      format.js
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/files_helper.rb
module FilesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nama</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/orders/_dropzone.html.erb
<div class="upload-wrapper">
    <%= form_with url: orders_path(format: :js), remote: true, local: false, class: "dropzone", id: "my-awesome-dropzone" do |form| %>
    <% end %>
</div>

<script>
    
    Dropzone.options.myAwesomeDropzone = {
        paramName: "file", // The name that will be used to transfer the file
        dictDefaultMessage: "Clique ou arraste para enviar arquivos",
        dictFileTooBig: "Arquivo muito grande. Limite: 20mb",
        maxFilesize: 20, // MB
        success: response => eval(response.xhr.response)
    };
</script>

app/views/orders/_order.html.erb
<tr>
    <td>Pedido <%= order.id %></td>
    <td> <%= order.created_at.strftime('%m/%d/%Y') %></td>
    <td><%= number_to_currency(order.value, :unit => "R$ ", :separator => ",", :delimiter => ".") %></td>
    <td><%= link_to "Visualizar", order_path(order) %></td>
</tr>

app/views/orders/create.js.erb
$("#orders-wrapper tbody").prepend("<%= j render @order %>");

app/views/orders/index.html.erb
<div class="container">
  <div style="margin: 15px">
    <h1>Gerenciar pedidos</h2>
  </div>
  <%= render "dropzone" %>
  <div id="orders-wrapper" >
    <table class="table">
        <thead>
            <tr>
                <th>Pedido</th>
                <th>Data</th>
                <th>Valor total</th>
                <th>Detalhes</th>
            <tr>
        <thead>
        <tbody>
          <%= render @orders %>
          <% if @orders.empty? %>
            <tr>
              <td>Nenhum arquivo enviado.</td>
            </tr>
          <% end %>
        </tbody>
      </thead>
    </table>

  <div>
</div>

app/views/orders/show.html.erb
<div class="container">
    <h1>Pedido <%= @order.id %></h1>
    <div>
        <table class="table shadow">
            <thead>
                <tr>
                    <th>Comprador</th>
                    <th>Descrição</th>
                    <th>Preço Unitário</th>
                    <th>Quantidade</th>
                    <th>Endereço</th>
                    <th>Fornecedor</th>
                <tr>
            <thead>
            <tbody>
                <% @order.items.each do |item| %>
                    <tr>
                        <td><%= item.client.name %></td>
                        <td><%= item.product.description %></td>
                        <td><%= number_to_currency(item.product.price, :unit => "R$ ", :separator => ",", :delimiter => ".") %></td>
                        <td><%= item.quantity %></td>
                        <td><%= item.supplier.address %></td>
                        <td><%= item.supplier.name %></td>
                    </tr>
                <% end %>
                <tr>
                <td></td>
                <td align="right" ><strong>Total: </strong></td>
                <td><%= number_to_currency(@order.value, :unit => "R$ ", :separator => ",", :delimiter => ".") %></td>
                <td></td>
                <td></td>
                <td></td>
                <tr>
            </tbody>
        </table>
        <%= link_to "Voltar", orders_path, class: "btn btn-info" %>
    <div>
</div>